etcd_cluster_token: test_patroni
etcd_init_cluster:
  - { ip: "172.28.128.4", host: "willion-ubuntu-db1" } 
  - { ip: "172.28.128.5", host: "willion-ubuntu-db2" }
  - { ip: "172.28.128.6", host: "willion-ubuntu-db3" }

etcd_hostname_ip: "{{ ansible_eth1.ipv4.address }}"  
patroni_hostname_ip: "{{ ansible_eth1.ipv4.address }}"

patroni_etcd_hosts:
  - 172.28.128.4:2379
  - 172.28.128.5:2379
  - 172.28.128.6:2379

postgresql_version: 14
patroni_postgresql_version: 14

postgresql_postgres_password: my_pass
postgresql_add_repo: false

patroni_cluster_name: patroni_test

patroni_replication_password: my_pass_replication
patroni_postgres_password: my_pass


patroni_postgresql_data_dir: /data
patroni_encoding: UTF8
patroni_locale: ru_RU.UTF-8