- name: include vars {{ ansible_os_family | lower }}.yml
  include_vars: "{{ ansible_os_family | lower }}.yml"
  tags:
  - postgresql::install
  - postgresql::init
  - postgresql::hba
  - postgresql::conf
  - postgresql::start
  - postgresql::ext
  - postgresql::user
  - postgresql::db
  - patroni::install
  - patroni::patroni-status

- name: include vars postgresql-conf.yaml
  include_vars: "postgresql-conf.yaml"
  tags:
  - postgresql::conf
  - postgresql::init
  - patroni::install

- name: Include postgresql-install instructions {{ ansible_os_family }}
  include_tasks: postgresql/install-{{ ansible_os_family }}.yml ## Debian RedHat
  tags:
  - postgresql::install

- name: Include extension timescaledb instructions {{ ansible_os_family }}
  include_tasks: extension/timescaledb.yml
  when:
  - postgresql_timescaledb_install
  tags:
  - postgresql::timescaledb

- name: Include patroni-install instructions
  include_tasks: patroni/patroni-install.yml
  tags:
  - patroni::install
  when:
  - postgresql_cluster

- name: Include patroni-check instructions
  include_tasks: patroni/patroni-check.yml
  tags:
  - patroni::patroni-status
  when:
  - postgresql_cluster

- name: Include postgresql-init instructions
  include_tasks: postgresql/postgresql-init.yml
  tags:
  - postgresql::init

- name: Include postgresql-hba instructions
  include_tasks: postgresql/postgresql-hba.yml
  tags:
  - postgresql::hba

- name: Include postgresql-conf instructions
  include_tasks: postgresql/postgresql-conf.yml
  tags:
  - postgresql::conf
  when:
  - not postgresql_cluster

- name: Include postgresql-start instructions
  include_tasks: postgresql/postgresql-start.yml
  tags:
  - postgresql::start
  when:
  - not postgresql_cluster

- name: Include postgresql-usr instructions
  include_tasks: postgresql/postgresql-usr.yml
  tags:
  - postgresql::user

- name: Include postgresql-ext instructions
  include_tasks: postgresql/postgresql-ext.yml
  tags:
  - postgresql::ext

- name: Include postgresql-db instructions
  include_tasks: postgresql/postgresql-db.yml
  tags:
  - postgresql::db
