- hosts: patroni_cluster
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
  - name: Distribution major version
    debug: msg="{{ ansible_all_ipv4_addresses }}"
  - name: Distribution major version
    debug: msg="{{ ansible_default_ipv4.address }}"
  - name: Distribution major version
    debug: msg="{{ ansible_eth1.ipv4.address }}"  
  - name: unicast
    debug: msg="{% set ns = {{interface_var_name}} %}{% for host in groups['patroni_cluster'] %}{% if host ==  ns %}:(host was {{ hostvars[host]['inventory_hostname'] }}) {{hostvars[host]['inventory_hostname']}} {% endif %} {% endfor %}"
    vars:
      interface_var_name: "{{ ansible_default_ipv4.address }}"