- hosts: patroni_cluster
  become: true
  roles:
  - role: etcd
    tags: etcd
  - role: postgresql
    tags: postgresql

- hosts: centos_patroni_cluster
  become: true
  roles:
  - role: etcd
    tags: etcd
  - role: postgresql
    tags: postgresql

