__psycopg2: "{{ 'python-psycopg2' if ( ansible_distribution_major_version == '10' and ansible_distribution == 'Debian' ) or ( ansible_distribution_major_version < '18' and ansible_distribution == 'Ubuntu' ) else 'python3-psycopg2' }}"
postgresql_packages:
  - postgresql-{{ postgresql_version }}
  - postgresql-client-{{ postgresql_version }}
  - postgresql-server-dev-{{ postgresql_version }}
  - postgresql-contrib-{{ postgresql_version }}
  - "{{ __psycopg2 }}"

postgresql_apt_repository_keys:
  - key: "http://www.postgresql.org/media/keys/ACCC4CF8.asc"  # postgresql repository apt key
postgresql_apt_repository:
  - repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
postgresql_apt_filename: "postgresql"

postgresql_unix_socket_dir: "/var/run/postgresql"

postgresql_bin: "/usr/lib/postgresql/{{ postgresql_version }}/bin"

postgresql_conf: "/etc/postgresql/{{ postgresql_version }}/main"

postgresql_service: "postgresql@{{ postgresql_version }}-main"
