---
__postgresql_global_conf:
 - {option: "listen_addresses", value: "*"}
 - {option: "port", value: "{{ postgresql_port }}"}

__postgresql_parameters:
 archive_mode: "off"
 archive_timeout: 1800s
 auto_explain.log_analyze: "true"
 auto_explain.log_buffers: "true"
 auto_explain.log_min_duration: 3s
 auto_explain.log_nested_statements: "true"
 auto_explain.log_timing: "false"
 auto_explain.log_triggers: "true"
 auto_explain.log_verbose: "true"
 autovacuum: "on"
 autovacuum_analyze_scale_factor: 0.02
 autovacuum_max_workers: "{{ 4 if ansible_facts['processor_vcpus'] > 8 else 2 }}"
 autovacuum_naptime: 1s
 autovacuum_vacuum_cost_delay: 2
 autovacuum_vacuum_cost_limit: 1000
 autovacuum_vacuum_scale_factor: 0.01
 checkpoint_completion_target: 0.9
 checkpoint_timeout: 5min
 default_statistics_target: 1000
 effective_cache_size: "{{ (ansible_facts['memtotal_mb'] * 0.7)| int }}MB"
 effective_io_concurrency: 200
 full_page_writes: "on"
 hot_standby: "on"
 hot_standby_feedback: "off"
 huge_pages: try
 log_checkpoints: "on"
 log_destination: stderr
 log_directory: log
 log_filename: postgresql-%Y-%m-%d.log
 log_line_prefix: "%m pid=[%p] sql_state=%e user=%u host=%r"
 log_lock_waits: "on"
 log_rotation_age: 1d
 log_rotation_size: 0
 log_temp_files: 0
 log_truncate_on_rotation: "on"
 logging_collector: "on"
 maintenance_work_mem: "{{ '2GB' if ansible_facts['memtotal_mb'] < 8000  else '4GB' }}"
 max_connections: 300
 max_files_per_process: 4096
 max_locks_per_transaction: 64
 max_parallel_maintenance_workers: "{{ 4 if ansible_facts['processor_vcpus'] > 8 else  (ansible_facts['processor_vcpus']/2)| int }}"
 max_parallel_workers: "{{ ansible_facts['processor_vcpus'] }}"
 max_parallel_workers_per_gather: "{{ 4 if ansible_facts['processor_vcpus'] > 8 else  (ansible_facts['processor_vcpus']/2)| int }}"
 max_prepared_transactions: 0
 max_replication_slots: 15
 max_standby_streaming_delay: 30s
 max_wal_senders: 15
 max_wal_size: 4GB
 max_worker_processes: "{{ ansible_facts['processor_vcpus'] }}"
 min_wal_size: 1GB
 old_snapshot_threshold: 60min
 password_encryption: md5
 pg_stat_statements.max: 10000
 pg_stat_statements.save: "off"
 pg_stat_statements.track: all
 random_page_cost: 1.1
 seq_page_cost: 1
 shared_buffers: "{{ (ansible_facts['memtotal_mb'] * 0.3)| int }}MB"
 shared_preload_libraries: pg_stat_statements,auto_explain
 superuser_reserved_connections: 5
 synchronous_commit: "off"
 track_activities: "on"
 track_counts: "on"
 track_functions: all
 track_io_timing: "on"
 unix_socket_directories: "{{ postgresql_unix_socket_dir }}"
 wal_buffers: 32MB
 wal_compression: "on"
 wal_level: replica
 wal_log_hints: "on"
 wal_receiver_status_interval: 10s
 work_mem: 32MB

__postgresql_extensions:
 - {ext: "pg_stat_statements", db: "postgres", state: "present"}
 - {ext: "pg_stat_statements", db: "template1", state: "present"}
 - {ext: "pg_buffercache", db: "template1", state: "present"}
 - {ext: "pgrowlocks", db: "template1", state: "present"}
 - {ext: "pgstattuple", db: "template1", state: "present"}
 - {ext: "dblink", db: "template1", state: "present"}
