__psycopg2: "{{ 'python-psycopg2' if ( ansible_os_family == 'RedHat' and ansible_distribution_major_version < '8')  else 'python3-psycopg2' }}"
postgresql_packages:
  - postgresql{{ postgresql_version }}
  - postgresql{{ postgresql_version }}-server
  - postgresql{{ postgresql_version }}-contrib
  - postgresql{{ postgresql_version }}-devel
  - postgresql{{ postgresql_version }}-libs
  - "{{ __psycopg2 }}"

postgresql_yum_repo_url: "https://download.postgresql.org/pub/repos/yum/reporpms/{{ 'F' if ansible_distribution|lower == 'fedora' else 'EL' }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm"

postgresql_bin_debian: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_bin_redhat: "/usr/pgsql-{{ postgresql_version }}/bin"
postgresql_bin: "{{ postgresql_bin_debian if ansible_os_family == 'Debian' else postgresql_bin_redhat }}"
postgresql_unix_socket_dir: "/var/run/postgresql"
postgresql_conf_debian: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_conf: "{{ postgresql_conf_debian if ansible_os_family == 'Debian' else  postgresql_data }}"

postgtresql_service_debian: "postgresql@{{ postgresql_version }}-main"
postgtresql_service_redhat: "postgresql-{{ postgresql_version }}"
postgresql_service: "{{ postgtresql_service_debian if ansible_os_family == 'Debian' else postgtresql_service_redhat }}"
