__psycopg2: "{{ 'python-psycopg2' if ( ansible_os_family == 'RedHat' and ansible_distribution_major_version < '8')  else 'python3-psycopg2' }}"
postgresql_packages:
  - postgresql{{ postgresql_version }}
  - postgresql{{ postgresql_version }}-server
  - postgresql{{ postgresql_version }}-contrib
  - postgresql{{ postgresql_version }}-devel
  - postgresql{{ postgresql_version }}-libs
  - "{{ __psycopg2 }}"
  - gcc
  - jq

postgresql_yum_repo_url: "https://download.postgresql.org/pub/repos/yum/reporpms/{{ 'F' if ansible_distribution|lower == 'fedora' else 'EL' }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm"

postgresql_bin: "/usr/pgsql-{{ postgresql_version }}/bin"
postgresql_unix_socket_dir: "/var/run/postgresql"
postgresql_conf: "{{ postgresql_data }}"

postgresql_service: "postgresql-{{ postgresql_version }}"
