---
- name: deploy pgbackrest
  include_tasks: pgbackrest/pgbackrest-install.yml
  tags:
    - pgbackrest::install
    - pgbackrest::conf

- name: deploy ssh keys
  include_tasks: pgbackrest/pgbackrest-ssh.yml
  tags:
    - pgbackrest::install

- name: deploy ssh knows_host keys
  include_tasks: pgbackrest/pgbackrest-sshkeys.yml
  loop: "{{ pgbackrest_nodes }}"
  tags:
    - pgbackrest::install

- name: deploy stanza
  include_tasks: pgbackrest/pgbackrest-stanza.yml
  tags:
    - pgbackrest::install
    - pgbackrest_stanza
