- name: create group {{ pgbackrest_user }}
  group:
    name: '{{ pgbackrest_user }}'
    system: yes
  tags:
    - pgbackrest_backup_user

- name: create user {{ pgbackrest_user }}
  user:
    name: '{{ pgbackrest_user }}'
    group: '{{ pgbackrest_user }}'
    password: "{{ '%s' | format(pgbackrest_password) |password_hash('sha256') }}"
    system: yes
    shell: /bin/bash
    update_password: on_create
  tags:
    - pgbackrest_backup_user

- name: allow to run a few scripts using sudo without password
  community.general.sudoers:
    name: postgres
    user: '{{ pgbackrest_user }}'
    nopassword: true
    runas: postgres
    validation: required
    state: present
    commands:
      - /var/lib/postgresql/script/check.sh
      - /var/lib/postgresql/script/backup.sh
  tags:
    - pgbackrest_backup_user
