- block:
  - name: generate pg_hba.conf
    template:
      src: pg_hba.conf.j2
      dest: "{{ postgresql_conf }}/pg_hba.conf"
      owner: postgres
      group: postgres
      mode: 0640
    notify: reload postgresql
    when:
      - ansible_os_family == "Debian"

  - name: generate pg_hba.conf
    template:
      src: pg_hba.conf.j2
      dest: "{{ postgresql_data }}/pg_hba.conf"
      owner: postgres
      group: postgres
      mode: 0640
    notify: reload postgresql
    when:
      - ansible_os_family == "RedHat"
  when:
    - not postgresql_cluster
  tags:
    - postgresql::hba

- name: generate pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_data }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0640
  notify: reload patroni hba
  when:
    - postgresql_cluster
  tags:
    - postgresql::hba
