- name: Prepare PostgreSQL | Who Master!?
  become: true
  become_user: postgres
  command: "{{ postgresql_bin }}/psql -p {{ postgresql_port }} -Aqtc 'SELECT pg_is_in_recovery();'"
  register: pg_is_in_recovery
  changed_when: false
  tags:
    - postgresql::db

- name: add extensions defaults to the databases postgres and template1
  become: true
  become_user: postgres
  postgresql_ext:
    db: "{{ item.db }}"
    name: "{{ item.ext }}"
    login_unix_socket: "{{ postgresql_unix_socket_dir }}"  # added in 2.8
    state: "{{ item.state|default('present') }}"
  with_items: "{{ __postgresql_extensions | flatten(1) }}"
  when:
    - pg_is_in_recovery.stdout == "f"
    - __postgresql_extensions is defined
    - __postgresql_extensions | length > 0
  tags:
    - postgresql::db

- name: create database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ item.db }}"
    owner: "{{ item.owner }}"
    login_unix_socket: "{{ postgresql_unix_socket_dir }}"
    template: "template1"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ postgresql_db | flatten(1) }}"
  when:
    - pg_is_in_recovery.stdout == "f"
    - postgresql_db is defined
    - postgresql_db | length > 0
  tags:
    - postgresql::db
