- name: Prepare PostgreSQL | Who Master!?
  become: true
  become_user: postgres
  command: "{{ postgresql_bin }}/psql -p {{ postgresql_port }} -Aqtc 'SELECT pg_is_in_recovery();'"
  register: pg_is_in_recovery
  changed_when: false
  tags:
    - postgresql::db

- name: create database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ item.db }}"
    owner: "{{ item.owner }}"
    login_unix_socket: "{{ postgresql_unix_socket_dir }}"
    port: "{{ postgresql_port }}"
    template: "template1"
    state: "{{ item.state|default('present') }}"
  ignore_errors: true
  with_items: "{{ postgresql_db | flatten(1) }}"
  when:
    - pg_is_in_recovery.stdout == "f"
    - postgresql_db is defined
    - postgresql_db | length > 0
  tags:
    - postgresql::db
