- name: Prepare PostgreSQL | Who Master!?
  become: true
  become_user: postgres
  command: "{{ postgresql_bin }}/psql -p {{ postgresql_port }} -Aqtc 'SELECT pg_is_in_recovery();'"
  register: pg_is_in_recovery
  changed_when: false
  tags:
    - postgresql::ext

- name: Add extensions to the databases
  become: true
  become_user: postgres
  postgresql_ext:
    db: "{{ item.db }}"
    name: "{{ item.ext }}"
    login_unix_socket: "{{ postgresql_unix_socket_dir }}"  # added in 2.8
    state: "{{ item.state|default('present') }}"
  with_items: "{{ postgresql_extensions | flatten(1) }}"
  when:
    - pg_is_in_recovery.stdout == "f"
    - postgresql_extensions is defined
    - postgresql_extensions | length > 0
  tags:
    - postgresql::ext
