---
- name: restart patroni
  systemd:
    name: patroni
    state: restarted
    enabled: true
    daemon_reload: true

- name: reload patroni
  systemd:
    name: patroni
    state: reloaded
    enabled: true
    daemon_reload: true
