__pgbackrest_global_conf:
  archive-async: y
  backup-standby: y
  compress-level: 6
  delta: y
  log-level-console: info
  log-level-file: info
  process-max: 3
  repo1-bundle-limit: 512MiB
  repo1-bundle-size: 8GiB
  repo1-bundle: y
  repo1-path: /pgbackrest/
  repo1-retention-full: 3
  repo1-s3-bucket: "{{ pgbackrest_s3_bucket }}"
  repo1-s3-endpoint: "{{ pgbackrest_s3_endpoint }}"
  repo1-s3-key-secret: "{{ pgbackrest_s3_secret }}"
  repo1-s3-key: "{{ pgbackrest_s3_access }}"
  repo1-s3-region: eu-central-1
  repo1-s3-uri-style: path
  repo1-s3-verify-tls: y
  repo1-type: s3
  start-fast: y
  archive-get-queue-max: 4GiB