---
postgresql_version: 12
postgresql_postgres_password: vault_pass_postgres
postgresql_add_repo: true # Добавление репы из официального репозитория true or false
postgresql_port: "5432"

postgresql_data: "/var/lib/postgresql/{{ postgresql_version }}"
postgresql_log: "/var/log/postgresql/postgresql-{{ postgresql_version }}.log"

postgresql_parameters: {}
# example:
#postgresql_parameters:
#   max_connections: 122
#   another_parameter: another_value

postgresql_global_conf:
 - {option: "listen_addresses", value: "*"}
 - {option: "port", value: "{{ postgresql_port }}"}

postgresql_pg_hba:
 - {type: "local", database: "all", user: "all", address: "", method: "trust"}
 - {type: "host", database: "all", user: "all", address: "127.0.0.1/32", method: "trust"}
 - {type: "host", database: "all", user: "all", address: "127.0.0.1/32", method: "md5"}
 - {type: "host", database: "all", user: "all", address: "all", method: "md5"}

postgresql_extensions:
 - {ext: "pg_stat_statements", db: "postgres", state: "present"}
 - {ext: "pg_stat_statements", db: "template1", state: "present"}
 - {ext: "pg_buffercache", db: "template1", state: "present"}
 - {ext: "pgrowlocks", db: "template1", state: "present"}
 - {ext: "pgstattuple", db: "template1", state: "present"}
 - {ext: "dblink", db: "template1", state: "present"}

postgresql_users:
 - { user: "postgres", pass: "{{ postgresql_postgres_password }}", flag: "SUPERUSER", state: "present"}
# - { user: "repuser", pass: "vault_pass_rep", flag: "LOGIN,REPLICATION", state: "present"}
# - { user: "app", pass: "vault_pass_app", flag: "LOGIN,CREATEDB,CREATEROLE", state: "present"}

postgresql_members: #{}
 - { user: "repuser", group: "pg_monitor"}
# - { user: "app", group: ["pg_monitor", "pg_read_all_stats"]}

postgresql_db: #{}
 - {db: "app", owner: "postgres", state: "present"}
