---
- name: include vars {{ ansible_os_family | lower }}.yml
  include_vars: "{{ ansible_os_family | lower }}.yml"
  tags:
    - pgbackrest::install

- name: include vars global.yml
  include_vars: "global.yml"
  tags:
    - pgbackrest::install
    - pgbackrest::conf

- name: Include pgbackrest tasks {{ ansible_os_family }}
  include_tasks: pgbackrest/pgbackrest.yml
  when:
    - pgbackrest
  tags:
    - pgbackrest::install
    - pgbackrest::conf
    - pgbackrest::statza
