- name: restart postgresql
  systemd:
    name: "{{ postgresql_service }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: start postgresql
  systemd:
    name: "{{ postgresql_service }}"
    state: started

- name: reload postgresql
  systemd:
    name: "{{ postgresql_service }}"
    state: reloaded
    enabled: yes
    daemon_reload: yes

- name: restart patroni
  systemd:
    name: patroni
    state: restarted
    enabled: true
    daemon_reload: true

- name: reload patroni
  systemd:
    name: patroni
    state: reloaded
    enabled: true
    daemon_reload: true
