- name: Prepare PostgreSQL | check PostgreSQL is started
  become: true
  become_user: postgres
  command: "{{ postgresql_bin }}/pg_isready -p {{ postgresql_port }}"
  register: pg_isready_result
  until: pg_isready_result.rc == 0
  retries: 30
  delay: 10
  changed_when: false
  tags:
    - patroni::patroni-status

- block:
    - name: Check postgresql cluster health
      run_once: true
      become: true
      become_user: postgres
      command: "patronictl -c {{ postgresql_patroni_config_dir }}/config.yml list"
      register: patronictl_result
      environment:
        PATH: "/usr/bin:/usr/local/bin"
      changed_when: false

    - name: PostgreSQL Cluster health
      run_once: true
      debug:
        var: patronictl_result.stdout_lines
  ignore_errors: true
  when:
    - ansible_os_family == "Debian"
  tags:
    - patroni::patroni-status

- block:
    - name: Check postgresql cluster health
      run_once: true
      become: true
      become_user: postgres
      command: "patronictl -c {{ postgresql_patroni_config_dir }}/patroni.yml list"
      register: patronictl_result
      environment:
        PATH: "/usr/bin:/usr/local/bin"
      changed_when: false

    - name: PostgreSQL Cluster health
      run_once: true
      debug:
        var: patronictl_result.stdout_lines
  ignore_errors: true
  when:
    - ansible_os_family == "RedHat"
  tags:
    - patroni::patroni-status
