- name: install packages from apt
  apt:
    name: patroni={{ postgresql_patroni_version }}
    update_cache: yes
    cache_valid_time: 3600
  when:
    - ansible_os_family == "Debian"
  tags:
    - patroni::install

- name: install packages from rpm
  package:
    name: "patroni-etcd-{{ postgresql_patroni_version }}"
    update_cache: yes
    state: present
  when:
    - ansible_os_family == "RedHat"
  tags:
    - patroni::install

- name: create log directory patroni
  file:
    path: /var/log/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: 0755
  tags:
    - patroni::install

- name: check create {{ postgresql_data_dir }}
  stat: path={{ postgresql_data_dir }}
  register: check_postgresql_data_dir
  changed_when: false
  tags:
    - patroni::install

- name: create folder postgresql data
  file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  tags:
    - patroni::install

- name: ensure a locale exists
  locale_gen:
    name: "{{ postgresql_locale }}"
    state: present
  when:
    - ansible_os_family == "Debian"
  tags:
    - patroni::install

- name: create folder patroni
  file:
    path: "{{ postgresql_patroni_config_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  tags:
    - patroni::install

- name: configure patroni Debian
  template:
    src: patroni.yml.j2
    dest: "{{ postgresql_patroni_config_dir }}/config.yml"
    owner: postgres
    group: postgres
    mode: "0644"
  notify: reload patroni
  when:
    - ansible_os_family == "Debian"
  tags:
    - patroni::install

- name: configure patroni RedHat
  template:
    src: patroni.yml.j2
    dest: "{{ postgresql_patroni_config_dir }}/patroni.yml"
    owner: postgres
    group: postgres
    mode: "0644"
  notify: reload patroni
  when:
    - ansible_os_family == "RedHat"
  tags:
    - patroni::install

- name: ensure patroni running
  service:
    name: patroni
    daemon_reload: yes
    state: started
    enabled: yes
  tags:
    - patroni::start
