- name: install packages from apt
  apt:
    name: patroni={{ patroni_version }}
    update_cache: yes
    cache_valid_time: 3600
  tags:
  - patroni::install

- name: create log directory patroni
  file:
    path: /var/log/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: 0755
  tags:
  - patroni::install

- name: check create {{ patroni_postgresql_data_dir }}
  stat: path={{ patroni_postgresql_data_dir }}
  register: check_patroni_postgresql_data_dir
  changed_when: false
  tags:
  - patroni::install

- name: create folder postgresql data
  become_user: root
  file:
    path: "{{ patroni_postgresql_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  tags:
  - patroni::install

- name: ensure a locale exists
  locale_gen:
    name: "{{ patroni_locale }}"
    state: present
  tags:
  - patroni::install

- name: configure patroni
  template:
    src: patroni.yml.j2
    dest: "{{ patroni_config_dir }}/config.yml"
    owner: postgres
    group: postgres
    mode: "0644"
  notify: restart patroni
  tags:
  - patroni::install

- name: ensure patroni running
  service:
    name: patroni
    daemon_reload: yes
    state: started
    enabled: yes
  tags:
  - patroni::start
